const data = [
  {
    id: 1,
    category: "Aluminium et PVC",
    title: "Construction avec aluminium et PVC, bureautique et bâtiment.",
    images: [
      "/data/project/aluminium _pvc/1.jpg",
      "/data/project/aluminium _pvc/2.jpg",
      "/data/project/aluminium _pvc/3.jpg",
      "/data/project/aluminium _pvc/4.jpg",
      "/data/project/aluminium _pvc/5.jpg",
      "/data/project/aluminium _pvc/6.jpg",
      "/data/project/aluminium _pvc/7.jpg",
      "/data/project/aluminium _pvc/8.jpg",
      "/data/project/aluminium _pvc/9.jpg",
      "/data/project/aluminium _pvc/10.jpg",
      "/data/project/aluminium _pvc/11.jpg",
      "/data/project/aluminium _pvc/12.jpg",
      "/data/project/aluminium _pvc/13.jpg",
      "/data/project/aluminium _pvc/15.jpg",
      "/data/project/aluminium _pvc/16.jpg",
    ],
  },
  {
    id: 2,
    category: "Aménagement faux plafond",
    title:
      "Aménagement avec une gamme de faux plafonds, revêtements en MDF et placoplâtre aquaplanes, ainsi que l'isolation phonique et thermique.",
    images: [
      "/data/project/aménagement_ faux_plafond/1.jpg",
      "/data/project/aménagement_ faux_plafond/2.jpg",
      "/data/project/aménagement_ faux_plafond/3.jpg",
      "/data/project/aménagement_ faux_plafond/4.jpg",
      "/data/project/aménagement_ faux_plafond/5.jpg",
      "/data/project/aménagement_ faux_plafond/6.jpg",
      "/data/project/aménagement_ faux_plafond/7.jpg",

      "/data/project/aménagement_ faux_plafond/9.jpg",
      "/data/project/aménagement_ faux_plafond/10.jpg",
      "/data/project/aménagement_ faux_plafond/11.jpg",
      "/data/project/aménagement_ faux_plafond/12.jpg",

      "/data/project/aménagement_ faux_plafond/14.jpg",
      "/data/project/aménagement_ faux_plafond/15.jpg",
      "/data/project/aménagement_ faux_plafond/16.jpg",
      "/data/project/aménagement_ faux_plafond/17.jpg",
      "/data/project/aménagement_ faux_plafond/18.jpg",
      "/data/project/aménagement_ faux_plafond/19.jpg",
      "/data/project/aménagement_ faux_plafond/20.jpg",
      "/data/project/aménagement_ faux_plafond/21.jpg",
      "/data/project/aménagement_ faux_plafond/22.jpg",
      "/data/project/aménagement_ faux_plafond/23.jpg",
      "/data/project/aménagement_ faux_plafond/24.jpg",
      "/data/project/aménagement_ faux_plafond/25.jpg",
      "/data/project/aménagement_ faux_plafond/26.jpg",
      "/data/project/aménagement_ faux_plafond/27.jpg",
      "/data/project/aménagement_ faux_plafond/28.jpg",

      "/data/project/aménagement_ faux_plafond/30.jpg",
      "/data/project/aménagement_ faux_plafond/31.jpg",
      "/data/project/aménagement_ faux_plafond/32.jpg",
      "/data/project/aménagement_ faux_plafond/33.jpg",
      "/data/project/aménagement_ faux_plafond/34.jpg",
      "/data/project/aménagement_ faux_plafond/35.jpg",
      "/data/project/aménagement_ faux_plafond/36.jpg",
      "/data/project/aménagement_ faux_plafond/37.jpg",
      "/data/project/aménagement_ faux_plafond/38.jpg",
      "/data/project/aménagement_ faux_plafond/39.jpg",
      "/data/project/aménagement_ faux_plafond/40.jpg",
      "/data/project/aménagement_ faux_plafond/41.jpg",
      "/data/project/aménagement_ faux_plafond/42.jpg",
      "/data/project/aménagement_ faux_plafond/43.jpg",
    ],
  },
  {
    id: 3,
    category: "Aménagement façade",
    title: "Aménagement mur-rideau, alucobond et façade en terre cuite",
    images: [
      "/data/project/aménagement_façade/1.jpg",
      "/data/project/aménagement_façade/2.jpg",
      "/data/project/aménagement_façade/3.jpg",
      "/data/project/aménagement_façade/4.jpg",
      "/data/project/aménagement_façade/5.jpg",
      "/data/project/aménagement_façade/6.jpg",
      "/data/project/aménagement_façade/7.jpg",
      "/data/project/aménagement_façade/8.jpg",
      "/data/project/aménagement_façade/9.jpg",
      "/data/project/aménagement_façade/10.jpg",
      "/data/project/aménagement_façade/11.jpg",
      "/data/project/aménagement_façade/12.jpg",
      "/data/project/aménagement_façade/13.jpg",
      "/data/project/aménagement_façade/15.jpg",
      "/data/project/aménagement_façade/16.jpg",
    ],
  },
  {
    id: 4,
    category: "Système Anti-incendie",
    title: "Installation des systèmes d'alarme et d'anti-incendie",
    images: [
      "/data/project/anti-incendie/1.jpg",
      "/data/project/anti-incendie/2.jpg",
      "/data/project/anti-incendie/3.jpg",
      "/data/project/anti-incendie/4.jpg",
      "/data/project/anti-incendie/5.jpg",
      "/data/project/anti-incendie/6.jpg",
      "/data/project/anti-incendie/7.jpg",
      "/data/project/anti-incendie/8.jpg",
      "/data/project/anti-incendie/9.jpg",
      "/data/project/anti-incendie/10.jpg",
      "/data/project/anti-incendie/11.jpg",
      "/data/project/anti-incendie/12.jpg",
    ],
  },
  {
    id: 5,
    category: "Groupe électrogène",
    title:
      "Installation et maintenance de groupe électrogène, d'onduleur industrielle, les armoires et câblage",
    images: [
      "/data/project/groupe_électrogène/1.jpg",
      "/data/project/groupe_électrogène/2.jpg",
      "/data/project/groupe_électrogène/3.jpg",
      "/data/project/groupe_électrogène/4.jpg",
      "/data/project/groupe_électrogène/5.jpg",
      "/data/project/groupe_électrogène/6.jpg",
      "/data/project/groupe_électrogène/7.jpg",
      "/data/project/groupe_électrogène/8.jpg",
      "/data/project/groupe_électrogène/9.jpg",
      "/data/project/groupe_électrogène/10.jpg",
      "/data/project/groupe_électrogène/11.jpg",
    ],
  },
  {
    id: 6,
    category: "Charpente métallique",
    title:
      "Fabrication et montage de charpente, portails métalliques industriels, rideau rapide et rayonnage industriel",
    images: [
      "/data/project/montage_charpente/1.jpg",
      "/data/project/montage_charpente/2.jpg",
      "/data/project/montage_charpente/3.jpg",
      "/data/project/montage_charpente/4.jpg",
      "/data/project/montage_charpente/5.jpg",
      "/data/project/montage_charpente/6.jpg",
      "/data/project/montage_charpente/7.jpg",
      "/data/project/montage_charpente/8.jpg",
      "/data/project/montage_charpente/9.jpg",
      "/data/project/montage_charpente/10.jpg",
      "/data/project/montage_charpente/11.jpg",
      "/data/project/montage_charpente/12.jpg",
      "/data/project/montage_charpente/13.jpg",
      "/data/project/montage_charpente/14.jpg",
      "/data/project/montage_charpente/15.jpg",
      "/data/project/montage_charpente/16.jpg",
      "/data/project/montage_charpente/17.jpg",
      "/data/project/montage_charpente/18.jpg",
      "/data/project/montage_charpente/19.jpg",
      "/data/project/montage_charpente/20.jpg",
      "/data/project/montage_charpente/21.jpg",
      "/data/project/montage_charpente/22.jpg",
      "/data/project/montage_charpente/23.jpg",
      "/data/project/montage_charpente/24.jpg",
      "/data/project/montage_charpente/25.jpg",
      "/data/project/montage_charpente/26.jpg",
      "/data/project/montage_charpente/27.jpg",
      "/data/project/montage_charpente/28.jpg",
      "/data/project/montage_charpente/29.jpg",
      "/data/project/montage_charpente/30.jpg",
      "/data/project/montage_charpente/31.jpg",
    ],
  },
  {
    id: 7,
    category: "Salle blanche",
    title: "Construction de salle blanche",
    images: [
      "/data/project/salle_blanche/1.jpg",
      "/data/project/salle_blanche/2.jpg",
      "/data/project/salle_blanche/3.jpg",
      "/data/project/salle_blanche/4.jpg",
      "/data/project/salle_blanche/5.jpg",
      "/data/project/salle_blanche/6.jpg",
      "/data/project/salle_blanche/7.jpg",
      "/data/project/salle_blanche/8.jpg",
      "/data/project/salle_blanche/9.jpg",
      "/data/project/salle_blanche/10.jpg",
      "/data/project/salle_blanche/11.jpg",
      "/data/project/salle_blanche/12.jpg",
      "/data/project/salle_blanche/13.jpg",
      "/data/project/salle_blanche/14.jpg",
      "/data/project/salle_blanche/15.jpg",
      "/data/project/salle_blanche/16.jpg",
      "/data/project/salle_blanche/17.jpg",
      "/data/project/salle_blanche/18.jpg",
    ],
  },
  {
    id: 8,
    category: "Traitement d'air",
    title:
      "Système de traitement d'air extérieur et intérieur, groupes de production d'eau Glacée (CHILLER) industrielle et bâtiment.",
    images: [
      "/data/project/traitement_air/1.jpg",
      "/data/project/traitement_air/2.jpg",
      "/data/project/traitement_air/3.jpg",
      "/data/project/traitement_air/4.jpg",
      "/data/project/traitement_air/5.jpg",
      "/data/project/traitement_air/6.jpg",

      "/data/project/traitement_air/8.jpg",
      "/data/project/traitement_air/9.jpg",
      "/data/project/traitement_air/10.jpg",
      "/data/project/traitement_air/11.jpg",
      "/data/project/traitement_air/12.jpg",
      "/data/project/traitement_air/13.jpg",
      "/data/project/traitement_air/14.jpg",
      "/data/project/traitement_air/15.jpg",

      "/data/project/traitement_air/17.jpg",
      "/data/project/traitement_air/18.jpg",
      "/data/project/traitement_air/19.jpg",
      "/data/project/traitement_air/20.jpg",
    ],
  },
  {
    id: 9,
    category: "Revêtement de sol",
    title: "Revêtement de sol en béton industriel, résine époxy et Gerflex",
    images: [
      "/data/project/sol-beton/1.jpg",
      "/data/project/sol-beton/2.jpg",
      "/data/project/sol-beton/3.jpg",
      "/data/project/sol-beton/4.jpg",
      "/data/project/sol-beton/5.jpg",
      "/data/project/sol-beton/6.jpg",
      "/data/project/sol-beton/7.jpg",
      "/data/project/sol-beton/8.jpg",
      "/data/project/sol-beton/9.jpg",
      "/data/project/sol-beton/10.jpg",
      "/data/project/sol-beton/11.jpg",
      "/data/project/sol-beton/12.jpg",
      "/data/project/sol-beton/13.jpg",
      "/data/project/sol-beton/14.jpg",
      "/data/project/sol-beton/15.jpg",
      "/data/project/sol-beton/16.jpg",
      "/data/project/sol-beton/17.jpg",
      "/data/project/sol-beton/18.jpg",
      "/data/project/sol-beton/19.jpg",
      "/data/project/sol-beton/20.jpg",
      "/data/project/sol-beton/21.jpg",
      "/data/project/sol-beton/22.jpg",
      "/data/project/sol-beton/23.jpg",
      "/data/project/sol-beton/24.jpg",
      "/data/project/sol-beton/25.jpg",
      "/data/project/sol-beton/26.jpg",
      "/data/project/sol-beton/27.jpg",
      "/data/project/sol-beton/28.jpg",
      "/data/project/sol-beton/29.jpg",
      "/data/project/sol-beton/30.jpg",
      "/data/project/sol-beton/31.jpg",
      "/data/project/sol-beton/32.jpg",
      "/data/project/sol-beton/33.jpg",
      "/data/project/sol-beton/34.jpg",
      "/data/project/sol-beton/35.jpg",
      "/data/project/sol-beton/36.jpg",
      "/data/project/sol-beton/37.jpg",
      "/data/project/sol-beton/38.jpg",
      "/data/project/sol-beton/39.jpg",
      "/data/project/sol-beton/40.jpg",
      "/data/project/sol-beton/41.jpg",
      "/data/project/sol-beton/42.jpg",
    ],
  },
  {
    id: 10,
    category: "Construction médical",
    title: "Construction médical",
    images: [
      "/data/project/medical/2.jpg",
      "/data/project/medical/1.jpg",
      "/data/project/medical/3.jpg",
      "/data/project/medical/4.jpg",

      "/data/project/medical/7.jpg",
      "/data/project/medical/8.jpg",
      "/data/project/medical/9.jpg",
      "/data/project/medical/10.jpg",
      "/data/project/medical/11.jpg",
      "/data/project/medical/12.jpg",
      "/data/project/medical/13.jpg",
      "/data/project/medical/14.jpg",
      "/data/project/medical/15.jpg",
      "/data/project/medical/16.jpg",
      "/data/project/medical/17.jpg",
      "/data/project/medical/18.jpg",
      "/data/project/medical/19.jpg",
      "/data/project/medical/20.jpg",
      "/data/project/medical/21.PNG",
      "/data/project/medical/22.PNG",
      "/data/project/medical/23.jpg",
    ],
  },
  {
    id: 11,
    category: "Camera surveillance",
    title:
      "Installation des caméras de surveillance, système d'alarme et obstacle automatique",
    images: [
      "/data/project/camera/1.jpg",
      "/data/project/camera/2.jpg",
      "/data/project/camera/3.jpg",
      "/data/project/camera/4.jpg",
      "/data/project/camera/5.jpg",
      "/data/project/camera/6.jpg",
      "/data/project/camera/7.jpg",
      "/data/project/camera/8.jpg",
      "/data/project/camera/9.jpg",
      "/data/project/camera/10.jpg",
      "/data/project/camera/11.jpg",
      "/data/project/camera/12.jpg",
      "/data/project/camera/13.jpg",
      "/data/project/camera/14.jpg",
    ],
  },
  {
    id: 12,
    category: "Panneau publicitaire",
    title: "Installation de panneau publicitaire et totem LED publicitaire",
    images: [
      "/data/project/panneau/1.jpg",
      "/data/project/panneau/2.jpg",
      "/data/project/panneau/3.jpg",
      "/data/project/panneau/4.jpg",
      "/data/project/panneau/5.jpg",
      "/data/project/panneau/6.jpg",
      "/data/project/panneau/7.jpg",
      "/data/project/panneau/8.jpg",
      "/data/project/panneau/9.jpg",
      "/data/project/panneau/10.jpg",
    ],
  },
];

export default data;
